import crypto from 'crypto';
import { Express, Request, Response, NextFunction } from 'express';
import { db } from './db';

const SESSION_TTL=1000*60*60*12;
const SESSION_SECRET=process.env.SESSION_SECRET||'change-this-secret-in-vercel';
function sign(value:string){return crypto.createHmac('sha256',SESSION_SECRET).update(value).digest('base64url')}
function issueSession(userId:string){const payload=Buffer.from(JSON.stringify({sub:userId,exp:Date.now()+SESSION_TTL})).toString('base64url');return `${payload}.${sign(payload)}`}
function verifySession(token:string){try{const[body,sig]=token.split('.');if(!body||!sig)return null;const expected=Buffer.from(sign(body));const actual=Buffer.from(sig);if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))return null;const data=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));return data.exp>Date.now()?String(data.sub):null}catch{return null}}
function cookieToken(req:Request){const raw=req.headers.cookie||'';const match=raw.split(';').map(x=>x.trim()).find(x=>x.startsWith('sb_session='));return match?.slice('sb_session='.length)||null}
export function getSessionUser(req:Request){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'')||cookieToken(req);if(!token)return null;const userId=verifySession(token);if(!userId)return null;const users=(db as any).getUsers?.() as any[]|undefined;const user=users?.find((u:any)=>u.id===userId);return user?db.publicUser(user):null}
export async function requireAuth(req:Request,res:Response,next:NextFunction){try{await db.waitReady();const user=getSessionUser(req);if(!user)return res.status(401).json({error:'Authentication required'});(req as any).user=user;next()}catch(err){console.error('[Auth]',err);res.status(503).json({error:'Database unavailable'})}}
export function requireRole(...roles:string[]){return async(req:Request,res:Response,next:NextFunction)=>{try{await db.waitReady();const user=(req as any).user||getSessionUser(req);if(!user||!roles.includes(user.role))return res.status(403).json({error:'Insufficient permissions'});(req as any).user=user;next()}catch(err){res.status(503).json({error:'Database unavailable'})}}}
export function registerAuthRoutes(app:Express){
 app.post('/api/auth/register',async(req,res)=>{try{await db.waitReady();const{salutation,name,phone,wing,flat,password}=req.body;if(!['Mr','Mrs','Ms'].includes(salutation)||!name||!phone||!wing||!flat||!password||password.length<6)return res.status(400).json({error:'Salutation, name, phone, wing, flat and a 6+ character password are required.'});const user=db.createResident({salutation,name,phone,wing,flat,password});const token=issueSession(user.id);res.setHeader('Set-Cookie',`sb_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${SESSION_TTL/1000}; Secure`);res.status(201).json({user:db.publicUser(user),token})}catch(e:any){res.status(400).json({error:e.message||'Registration failed'})}});
 app.post('/api/auth/login',async(req,res)=>{try{await db.waitReady();const{role,phone,admin_id,password}=req.body;const user=role==='admin'?db.findAdmin(admin_id,phone):db.findUserByPhone(phone||'');if(!user||(role==='admin'&&user.role!=='admin')||!db.verifyUser(user,password||''))return res.status(401).json({error:'Invalid credentials'});const token=issueSession(user.id);res.setHeader('Set-Cookie',`sb_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${SESSION_TTL/1000}; Secure`);res.json({user:db.publicUser(user),token})}catch(e){console.error('[Login]',e);res.status(503).json({error:'Database unavailable'})}});
 app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie','sb_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0; Secure');res.json({success:true})});
 app.get('/api/auth/me',requireAuth,(req,res)=>res.json({user:(req as any).user}));
}