import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, CheckCircle2, ChevronRight, Clock3, MapPin, RefreshCw, Users, X } from 'lucide-react';
import { Complaint, UserAccount } from '../types';

interface Props { currentUser: UserAccount; onBack: () => void; }
const keyFor=(c:Complaint)=>`${(c.category||'General').toLowerCase()}::${(c.normalized_summary||c.original_message||'Society issue').toLowerCase().replace(/\s+/g,' ').trim()}`;
export const IssueDirectory:React.FC<Props>=({onBack})=>{
 const [mode,setMode]=useState<'ongoing'|'solved'>((localStorage.getItem('sb_issue_view') as any)==='solved'?'solved':'ongoing');
 const [items,setItems]=useState<Complaint[]>([]); const [selected,setSelected]=useState<Complaint[]|null>(null); const [title,setTitle]=useState(''); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/complaints',{cache:'no-cache'});if(r.ok)setItems(await r.json())}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const groups=useMemo(()=>{const map=new Map<string,Complaint[]>();items.filter(c=>mode==='solved'?c.status==='RESOLVED':c.status!=='RESOLVED').forEach(c=>{const k=keyFor(c);map.set(k,[...(map.get(k)||[]),c])});return [...map.values()].sort((a,b)=>b.length-a.length)},[items,mode]);
 const open=(group:Complaint[])=>{setSelected(group);setTitle(group[0]?.normalized_summary||group[0]?.category||'Society Issue')};
 return <div className="motion-page max-w-6xl mx-auto px-4 sm:px-6 py-7 sm:py-10"><button onClick={onBack} className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-rose-600 mb-4"><ArrowLeft className="w-3.5 h-3.5"/> Back to Home</button><div className="flex items-center justify-between gap-3 mb-6"><div><div className="flex items-center gap-2">{mode==='ongoing'?<Activity className="w-6 h-6 text-rose-500"/>:<CheckCircle2 className="w-6 h-6 text-emerald-500"/>}<h1 className="text-2xl sm:text-3xl font-black">{mode==='ongoing'?'Ongoing Issues':'Solved Issues'}</h1></div><p className="text-sm text-slate-500 mt-1">Browse common issues and see how many residents reported each one.</p></div><button onClick={load} className="p-2.5 rounded-xl bg-rose-50 text-rose-600"><RefreshCw className="w-4 h-4"/></button></div>
 <div className="grid grid-cols-2 gap-2 p-1.5 bg-white border border-rose-100 rounded-2xl mb-6"><button onClick={()=>{setMode('ongoing');localStorage.setItem('sb_issue_view','ongoing');setSelected(null)}} className={`py-3 rounded-xl text-sm font-black ${mode==='ongoing'?'bg-rose-500 text-white':'text-slate-500 hover:bg-rose-50'}`}>Ongoing</button><button onClick={()=>{setMode('solved');localStorage.setItem('sb_issue_view','solved');setSelected(null)}} className={`py-3 rounded-xl text-sm font-black ${mode==='solved'?'bg-emerald-500 text-white':'text-slate-500 hover:bg-emerald-50'}`}>Solved</button></div>
 {loading?<div className="bg-white rounded-3xl border border-rose-100 p-12 text-center text-sm text-slate-400">Loading issues...</div>:groups.length===0?<div className="bg-white rounded-3xl border border-rose-100 p-12 text-center"><CheckCircle2 className="w-10 h-10 mx-auto text-emerald-500"/><h2 className="font-black mt-3">No {mode} issues</h2></div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{groups.map((group,i)=><button key={i} onClick={()=>open(group)} className="text-left bg-white rounded-[26px] border border-rose-100 p-5 shadow-sm hover:-translate-y-1 hover:shadow-lg transition-all"><div className={`w-11 h-11 rounded-2xl flex items-center justify-center ${mode==='ongoing'?'bg-rose-50 text-rose-600':'bg-emerald-50 text-emerald-600'}`}>{mode==='ongoing'?<Activity className="w-5 h-5"/>:<CheckCircle2 className="w-5 h-5"/>}</div><div className="mt-4 text-[10px] uppercase tracking-wider font-black text-rose-500">{group[0]?.category||'General'}</div><h2 className="font-black text-slate-900 mt-1 line-clamp-3">{group[0]?.normalized_summary||group[0]?.original_message||'Society issue'}</h2><div className="mt-5 flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-xs font-black text-slate-600"><Users className="w-4 h-4 text-rose-500"/>{group.length} {group.length===1?'resident':'residents'}</span><ChevronRight className="w-5 h-5 text-slate-300"/></div><div className="text-[11px] text-slate-400 mt-2">Click to see affected residents</div></button>)}</div>}
 {selected&&<div className="fixed inset-0 z-[70] bg-slate-900/45 backdrop-blur-sm flex items-end sm:items-center justify-center p-3" onClick={()=>setSelected(null)}><div className="bg-white w-full max-w-2xl max-h-[88vh] overflow-y-auto rounded-[30px] shadow-2xl" onClick={e=>e.stopPropagation()}><div className="sticky top-0 z-10 bg-white/95 backdrop-blur border-b border-rose-100 p-5 flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-wider font-black text-rose-500">Affected residents</div><h2 className="text-xl font-black mt-1">{title}</h2><p className="text-xs text-slate-500 mt-1">{selected.length} resident{selected.length===1?'':'s'} reported this issue.</p></div><button onClick={()=>setSelected(null)} className="p-2 rounded-xl bg-rose-50 text-rose-600"><X className="w-5 h-5"/></button></div><div className="p-5 space-y-3">{selected.map(c=><div key={c.id} className="rounded-2xl border border-rose-100 bg-rose-50/40 p-4 flex gap-3"><div className="w-10 h-10 rounded-full bg-rose-100 text-rose-600 flex items-center justify-center font-black">{c.resident_name?.charAt(0)||'R'}</div><div><div className="font-black text-sm">{c.resident_name||'Resident'}</div><div className="text-xs text-slate-500 mt-1 inline-flex items-center gap-1"><MapPin className="w-3.5 h-3.5 text-rose-500"/>{c.wing||'Wing'} · Flat {c.resident_flat||'—'}</div><div className="text-xs text-slate-600 mt-2">Case {c.case_id} · {new Date(c.created_at).toLocaleDateString()} <Clock3 className="inline w-3 h-3 ml-1"/></div></div></div>)}</div></div></div>}
 </div>;
};