import React, { useEffect, useMemo, useState } from 'react';
import { Bell, BookOpen, CheckCircle2, Globe2, LogOut, Megaphone, MessageCircle, Sparkles } from 'lucide-react';
import { PortalNav } from './components/PortalNav';
import { AuthScreen } from './components/AuthScreen';
import { NoticeBoard } from './components/NoticeBoard';
import { ReminderCenter } from './components/ReminderCenter';
import { AppManual } from './components/AppManual';
import { ResidentReport } from './components/ResidentReport';
import { ResidentTracking } from './components/ResidentTracking';
import { CommandCenter } from './components/CommandCenter';
import { IssueIntelligenceModal } from './components/IssueIntelligenceModal';
import { ResolutionModal } from './components/ResolutionModal';
import { TwoMinuteTriage } from './components/TwoMinuteTriage';
import { MasterIssueModal } from './components/MasterIssueModal';
import { IssueGalaxy } from './components/IssueGalaxy';
import { SocietyPulse } from './components/SocietyPulse';
import { SearchModal } from './components/SearchModal';
import { ChatRoom } from './components/ChatRoom';
import { api } from './services/api';
import { extraApi } from './services/extraApi';
import { Complaint, MasterIssue, NotificationItem, UserAccount, Notice, Reminder, Language } from './types';

const LANGUAGES: {id:Language;label:string;native:string}[] = [
 {id:'english',label:'English',native:'English'},{id:'hindi',label:'Hindi',native:'हिन्दी'},{id:'marathi',label:'Marathi',native:'मराठी'},{id:'telugu',label:'Telugu',native:'తెలుగు'},{id:'gujarati',label:'Gujarati',native:'ગુજરાતી'},{id:'punjabi',label:'Punjabi',native:'ਪੰਜਾਬੀ'},{id:'bengali',label:'Bengali',native:'বাংলা'},{id:'hinglish',label:'Hinglish',native:'Hinglish'}
];
const HOME_COPY:Record<string,{tag:string;intro:string;sub:string;report:string;track:string;manual:string;notices:string;chat:string;manualSub:string;noticesSub:string;chatSub:string}>= {
 english:{tag:'Ek page, aapki baat. Seedha hum tak',intro:'What needs attention today?',sub:'Tell us in your own words. AI understands your complaint and helps the society team act faster.',report:'Report an issue',track:'Track my issues',manual:'App Manual',notices:'Society Notices',chat:'Society Chat',manualSub:'Learn how to report, track and verify a complaint.',noticesSub:'See announcements relevant to your home and society.',chatSub:'Connect with neighbours and share community updates.'},
 hindi:{tag:'एक पेज, आपकी बात। सीधा हम तक',intro:'आज किस चीज़ पर ध्यान चाहिए?',sub:'अपनी भाषा में बताइए। AI आपकी शिकायत समझकर सोसाइटी टीम को जल्दी कार्रवाई में मदद करता है।',report:'शिकायत दर्ज करें',track:'मेरी शिकायतें',manual:'ऐप मैनुअल',notices:'सोसाइटी नोटिस',chat:'सोसाइटी चैट',manualSub:'शिकायत दर्ज करने और ट्रैक करने की पूरी जानकारी।',noticesSub:'अपने घर और सोसाइटी के जरूरी नोटिस देखें।',chatSub:'पड़ोसियों से जुड़ें और समुदाय की बातें साझा करें।'},
 marathi:{tag:'एक पेज, तुमची बात. थेट आमच्यापर्यंत',intro:'आज कशाकडे लक्ष द्यायचे?',sub:'तुमच्या शब्दांत सांगा. AI तक्रार समजून सोसायटी टीमला जलद कृती करण्यात मदत करतो.',report:'तक्रार नोंदवा',track:'माझ्या तक्रारी',manual:'अॅप मॅन्युअल',notices:'सोसायटी नोटिस',chat:'सोसायटी चॅट',manualSub:'तक्रार नोंदवणे आणि ट्रॅक करण्यासाठी मार्गदर्शक.',noticesSub:'तुमच्या सोसायटीतील महत्त्वाच्या सूचना पहा.',chatSub:'शेजाऱ्यांशी संपर्क साधा आणि माहिती शेअर करा.'},
 telugu:{tag:'ఒక పేజీ, మీ మాట. నేరుగా మాకు',intro:'ఈరోజు దేనిపై దృష్టి పెట్టాలి?',sub:'మీ మాటల్లో చెప్పండి. AI మీ ఫిర్యాదును అర్థం చేసుకుని త్వరగా చర్యకు సహాయపడుతుంది.',report:'ఫిర్యాదు చేయండి',track:'నా ఫిర్యాదులు',manual:'యాప్ మాన్యువల్',notices:'సొసైటీ నోటీసులు',chat:'సొసైటీ చాట్',manualSub:'ఫిర్యాదు చేయడం మరియు ట్రాక్ చేయడం గురించి తెలుసుకోండి.',noticesSub:'మీకు సంబంధించిన సొసైటీ ప్రకటనలను చూడండి.',chatSub:'పొరుగువారితో కనెక్ట్ అయి సమాచారం పంచుకోండి.'},
 gujarati:{tag:'એક પેજ, તમારી વાત. સીધી અમારી સુધી',intro:'આજે કઈ બાબત પર ધ્યાન જોઈએ?',sub:'તમારી ભાષામાં કહો. AI તમારી ફરિયાદ સમજીને સોસાયટી ટીમને ઝડપી કાર્યવાહી કરવામાં મદદ કરે છે.',report:'ફરિયાદ કરો',track:'મારી ફરિયાદો',manual:'એપ મેન્યુઅલ',notices:'સોસાયટી નોટિસ',chat:'સોસાયટી ચેટ',manualSub:'ફરિયાદ નોંધવા અને ટ્રેક કરવા માટે માર્ગદર્શિકા.',noticesSub:'તમારા માટે મહત્વની સોસાયટી સૂચનાઓ જુઓ.',chatSub:'પડોશીઓ સાથે જોડાઓ અને માહિતી શેર કરો.'},
 punjabi:{tag:'ਇੱਕ ਪੇਜ, ਤੁਹਾਡੀ ਗੱਲ। ਸਿੱਧੀ ਸਾਡੇ ਤੱਕ',intro:'ਅੱਜ ਕਿਸ ਗੱਲ ਵੱਲ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ?',sub:'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦੱਸੋ। AI ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ ਸਮਝ ਕੇ ਤੇਜ਼ ਕਾਰਵਾਈ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',report:'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',track:'ਮੇਰੀਆਂ ਸ਼ਿਕਾਇਤਾਂ',manual:'ਐਪ ਮੈਨੂਅਲ',notices:'ਸੋਸਾਇਟੀ ਨੋਟਿਸ',chat:'ਸੋਸਾਇਟੀ ਚੈਟ',manualSub:'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰਨ ਅਤੇ ਟ੍ਰੈਕ ਕਰਨ ਲਈ ਗਾਈਡ।',noticesSub:'ਸੋਸਾਇਟੀ ਦੀਆਂ ਮਹੱਤਵਪੂਰਨ ਸੂਚਨਾਵਾਂ ਵੇਖੋ।',chatSub:'ਗੁਆਂਢੀਆਂ ਨਾਲ ਜੁੜੋ ਅਤੇ ਜਾਣਕਾਰੀ ਸਾਂਝੀ ਕਰੋ।'},
 bengali:{tag:'এক পেজ, আপনার কথা। সরাসরি আমাদের কাছে',intro:'আজ কোন বিষয়ে নজর দরকার?',sub:'নিজের ভাষায় বলুন। AI অভিযোগ বুঝে দ্রুত ব্যবস্থা নিতে সাহায্য করে।',report:'অভিযোগ করুন',track:'আমার অভিযোগ',manual:'অ্যাপ ম্যানুয়াল',notices:'সোসাইটি নোটিস',chat:'সোসাইটি চ্যাট',manualSub:'অভিযোগ করা এবং ট্র্যাক করার সহজ নির্দেশিকা।',noticesSub:'আপনার জন্য গুরুত্বপূর্ণ সোসাইটি বিজ্ঞপ্তি দেখুন।',chatSub:'প্রতিবেশীদের সঙ্গে যুক্ত হন এবং তথ্য শেয়ার করুন।'},
 hinglish:{tag:'Ek page, aapki baat. Seedha hum tak',intro:'Aaj kis cheez par dhyaan chahiye?',sub:'Apni language mein batao. AI complaint samajhta hai aur society team ko jaldi action lene mein help karta hai.',report:'Complaint karein',track:'Meri complaints',manual:'App Manual',notices:'Society Notices',chat:'Society Chat',manualSub:'Complaint report, track aur verify karne ka simple guide.',noticesSub:'Apne society ke important announcements dekhein.',chatSub:'Neighbours se connect karein aur community updates share karein.'}
};

export function App(){
 const [currentUser,setCurrentUser]=useState<UserAccount|null>(null); const [token,setToken]=useState<string|null>(localStorage.getItem('sb_token')); const [tab,setTab]=useState('home');
 const [complaints,setComplaints]=useState<Complaint[]>([]); const [masterIssues,setMasterIssues]=useState<MasterIssue[]>([]); const [notifications,setNotifications]=useState<NotificationItem[]>([]); const [notices,setNotices]=useState<Notice[]>([]); const [reminders,setReminders]=useState<Reminder[]>([]);
 const [activeComplaint,setActiveComplaint]=useState<Complaint|null>(null); const [activeMaster,setActiveMaster]=useState<MasterIssue|null>(null); const [resolvingComplaint,setResolvingComplaint]=useState<Complaint|null>(null); const [isTriageOpen,setIsTriageOpen]=useState(false); const [isSearchOpen,setIsSearchOpen]=useState(false); const [trackedCaseId,setTrackedCaseId]=useState('');
 const [language,setLanguage]=useState<Language>((localStorage.getItem('sb_language') as Language)||'english');
 useEffect(()=>{if(!token)return;fetch('/api/auth/me',{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setCurrentUser(d.user)).catch(()=>{localStorage.removeItem('sb_token');setToken(null);});},[token]);
 const refresh=async()=>{try{const[c,m,n]=await Promise.all([api.getComplaints(),api.getMasterIssues(),api.getNotifications()]);setComplaints(c);setMasterIssues(m);setNotifications(n);const[ns,rs]=await Promise.all([extraApi.getNotices().catch(()=>[]),extraApi.getReminders().catch(()=>[])]);setNotices(ns);setReminders(rs);}catch(e){console.warn(e)}};
 useEffect(()=>{if(currentUser)refresh()},[currentUser]); useEffect(()=>{if(!currentUser)return;const timer=setInterval(refresh,30000);return()=>clearInterval(timer)},[currentUser]);
 const setLang=(l:Language)=>{setLanguage(l);localStorage.setItem('sb_language',l)}; const logout=()=>{localStorage.removeItem('sb_token');setToken(null);setCurrentUser(null)};
 const unread=notifications.filter(n=>!n.read&&(!n.recipient_user_id||n.recipient_user_id===currentUser?.id)).length;
 const residentComplaints=useMemo(()=>currentUser?complaints.filter(c=>c.resident_id===currentUser.id||c.resident_flat===currentUser.flat):[],[complaints,currentUser]); const tracked=residentComplaints.find(c=>c.case_id===trackedCaseId)||residentComplaints[0]||({} as Complaint); const defaultMaster=masterIssues[0]||null;
 if(!currentUser)return <AuthScreen onAuthenticated={(user,t)=>{localStorage.setItem('sb_token',t);setToken(t);setCurrentUser(user);setTab(user.role==='resident'?'home':'dashboard')}}/>;
 const isAdmin=currentUser.role==='admin'||currentUser.role==='committee'; const markRead=async(n:NotificationItem)=>{await api.markNotificationRead(n.id);refresh()};
 const createNotice=async(n:Omit<Notice,'id'|'created_at'|'created_by'>)=>{await extraApi.createNotice({...n,created_by:currentUser.id});await refresh()}; const createReminder=async(r:Omit<Reminder,'id'|'created_at'>)=>{await extraApi.createReminder(r);await refresh()}; const updateReminder=async(id:string,status:Reminder['status'])=>{await extraApi.updateReminder(id,status);await refresh()}; const createTask=async(title:string)=>{await api.createComplaint({original_message:`Maintenance Task: ${title}`,resident_name:'Managing Committee',resident_flat:'Facility',wing:'B Wing',location_detail:'Infrastructure'});await refresh()};
 const c=HOME_COPY[language]||HOME_COPY.english;
 const HomeResident=()=> <div className="motion-page max-w-6xl mx-auto px-4 sm:px-6 py-6 sm:py-10">
  <section className="relative overflow-hidden rounded-[34px] bg-gradient-to-br from-rose-600 via-rose-500 to-pink-500 text-white p-6 sm:p-10 lg:p-12 shadow-[0_24px_70px_rgba(225,29,72,.22)] card-lift"><div className="absolute -right-20 -bottom-28 w-80 h-80 rounded-full border-[40px] border-white/10 animate-float-slow"/><div className="absolute right-20 top-8 w-10 h-10 rounded-full bg-white/10 animate-float-slow"/><div className="relative z-10 grid lg:grid-cols-[1.35fr_.65fr] gap-8 items-center"><div><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/15 border border-white/20 text-xs font-extrabold tracking-wide"><Sparkles className="w-4 h-4"/>{c.tag}</div><h1 className="mt-6 text-3xl sm:text-5xl lg:text-6xl font-black leading-[1.02]">Namaste, {currentUser.salutation||''} {currentUser.name}</h1><h2 className="mt-3 text-xl sm:text-2xl font-bold text-white/90">{c.intro}</h2><p className="mt-4 max-w-2xl text-sm sm:text-base text-white/80 leading-relaxed">{c.sub}</p><div className="mt-7 flex flex-col sm:flex-row gap-3"><button onClick={()=>setTab('report')} className="px-5 py-3.5 rounded-2xl bg-white text-rose-600 font-extrabold text-sm shadow-lg hover:-translate-y-0.5 transition-transform">{c.report}</button><button onClick={()=>setTab('issues')} className="px-5 py-3.5 rounded-2xl bg-white/10 border border-white/25 font-extrabold text-sm hover:bg-white/15 transition">{c.track}</button></div></div><div className="relative mx-auto w-56 h-56 sm:w-64 sm:h-64"><div className="absolute inset-0 rounded-[42%] rotate-6 bg-white/10 border border-white/15 animate-complaint-orbit"/><div className="absolute inset-6 rounded-[36%] -rotate-6 bg-white shadow-2xl flex flex-col items-center justify-center text-rose-600 card-lift"><div className="w-16 h-16 rounded-2xl bg-rose-50 flex items-center justify-center text-3xl animate-subtle-pulse">📮</div><div className="mt-3 font-black text-sm">SHIKAYAT</div><div className="text-xs font-bold text-slate-400">BOX</div><div className="mt-3 w-20 h-1.5 rounded-full bg-rose-100 overflow-hidden"><span className="block h-full w-2/3 bg-rose-500 animate-loading-bar"/></div></div></div></div></section>
  <section className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5 motion-rise">{[[residentComplaints.length,'My reports',''],[residentComplaints.filter(x=>x.status!=='RESOLVED').length,'Open issues','text-rose-600'],[residentComplaints.filter(x=>x.resident_confirmation==='RESOLVED_CONFIRMED').length,'Verified','text-emerald-600'],[unread,'Updates','text-pink-600']].map(([num,label,color])=><div key={String(label)} className="bg-white rounded-2xl border border-rose-100 p-4 card-lift"><div className={`text-2xl font-black ${color}`}>{num}</div><div className="text-[11px] text-slate-500 mt-1 font-bold">{label}</div></div>)}</section>
  <section className="mt-7"><div className="mb-4"><div className="text-[11px] uppercase tracking-wider font-black text-rose-500">Quick access</div><h2 className="text-xl sm:text-2xl font-black mt-1">Everything you need, in one place</h2></div><div className="grid md:grid-cols-3 gap-4"><button onClick={()=>setTab('manual')} className="group text-left rounded-[28px] min-h-48 p-5 sm:p-6 bg-gradient-to-br from-rose-50 via-white to-pink-50 border border-rose-100 card-lift motion-rise"><div className="w-12 h-12 rounded-2xl bg-white text-rose-600 flex items-center justify-center shadow-sm"><BookOpen className="w-6 h-6"/></div><h3 className="mt-7 text-lg font-black">{c.manual}</h3><p className="mt-2 text-sm text-slate-500 leading-5">{c.manualSub}</p><span className="inline-block mt-5 text-xs font-black text-rose-600 group-hover:translate-x-1 transition-transform">Open manual →</span></button><button onClick={()=>setTab('notices')} className="group text-left rounded-[28px] min-h-48 p-5 sm:p-6 bg-gradient-to-br from-orange-50 via-white to-rose-50 border border-rose-100 card-lift motion-rise"><div className="w-12 h-12 rounded-2xl bg-white text-rose-600 flex items-center justify-center shadow-sm"><Megaphone className="w-6 h-6"/></div><h3 className="mt-7 text-lg font-black">{c.notices}</h3><p className="mt-2 text-sm text-slate-500 leading-5">{c.noticesSub}</p><span className="inline-block mt-5 text-xs font-black text-rose-600 group-hover:translate-x-1 transition-transform">View notices →</span></button><button onClick={()=>setTab('chat')} className="group text-left rounded-[28px] min-h-48 p-5 sm:p-6 bg-gradient-to-br from-pink-50 via-white to-rose-50 border border-rose-100 card-lift motion-rise"><div className="w-12 h-12 rounded-2xl bg-white text-rose-600 flex items-center justify-center shadow-sm"><MessageCircle className="w-6 h-6"/></div><h3 className="mt-7 text-lg font-black">{c.chat}</h3><p className="mt-2 text-sm text-slate-500 leading-5">{c.chatSub}</p><span className="inline-block mt-5 text-xs font-black text-rose-600 group-hover:translate-x-1 transition-transform">Open chat →</span></button></div></section>
 </div>;
 const Notifications=()=> <div className="motion-page max-w-4xl mx-auto px-4 sm:px-6 py-8"><div className="mb-6"><h1 className="text-2xl font-black">Notifications</h1><p className="text-sm text-slate-500 mt-1">New complaints, SLA risk, notices and resolution updates.</p></div><div className="space-y-2">{notifications.filter(n=>!n.recipient_user_id||n.recipient_user_id===currentUser.id).map(n=><button key={n.id} onClick={()=>{markRead(n);if(n.complaint_id){const cc=complaints.find(x=>x.id===n.complaint_id);if(cc)setActiveComplaint(cc)}}} className={`w-full text-left bg-white rounded-2xl border p-4 flex gap-3 card-lift ${n.read?'border-slate-200':'border-rose-200 bg-rose-50/30'}`}><div className="w-9 h-9 rounded-xl bg-rose-50 flex items-center justify-center"><Bell className="w-4 h-4 text-rose-600"/></div><div className="flex-1"><div className="text-sm font-bold">{n.title}</div><div className="text-xs text-slate-600 mt-1">{n.message}</div><div className="text-[10px] text-slate-400 mt-2">{new Date(n.timestamp).toLocaleString()}</div></div>{!n.read&&<span className="w-2 h-2 rounded-full bg-rose-500 mt-2 notification-pop"/>}</button>)}{notifications.length===0&&<div className="bg-white border rounded-2xl p-10 text-center text-sm text-slate-500">You're all caught up.</div>}</div></div>;
 const Profile=()=> <div className="motion-page max-w-3xl mx-auto px-4 sm:px-6 py-8"><div className="bg-white border border-rose-100 rounded-3xl p-6 sm:p-8 shadow-[0_15px_50px_rgba(244,63,94,.06)]"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-2xl bg-rose-100 text-rose-600 flex items-center justify-center text-xl font-black">{currentUser.name.charAt(0)}</div><div><h1 className="text-xl font-black">{currentUser.name}</h1><p className="text-sm text-slate-500">{currentUser.flat||'Society admin'} · {currentUser.wing||currentUser.role}</p></div></div><div className="grid sm:grid-cols-2 gap-3 mt-7"><div className="rounded-2xl bg-rose-50/60 p-4"><div className="text-[10px] uppercase font-bold text-slate-400">Phone</div><div className="font-bold text-sm mt-1">{currentUser.phone||'—'}</div></div><div className="rounded-2xl bg-rose-50/60 p-4"><div className="text-[10px] uppercase font-bold text-slate-400">Role</div><div className="font-bold text-sm mt-1 capitalize">{currentUser.role}</div></div></div><div className="mt-7"><div className="flex items-center gap-2 font-bold text-sm"><Globe2 className="w-4 h-4 text-rose-600"/> Language</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3">{LANGUAGES.map(l=><button key={l.id} onClick={()=>setLang(l.id)} className={`p-3 rounded-xl border text-left ${language===l.id?'border-rose-400 bg-rose-50 text-rose-800':'border-slate-200 hover:bg-rose-50/50'}`}><div className="text-xs font-bold">{l.native}</div><div className="text-[10px] text-slate-400 mt-0.5">{l.label}</div></button>)}</div></div><button onClick={logout} className="mt-7 w-full h-11 rounded-xl bg-slate-100 hover:bg-red-50 hover:text-red-700 text-sm font-bold flex items-center justify-center gap-2"><LogOut className="w-4 h-4"/> Sign out</button></div></div>;
 let content:React.ReactNode;
 if(!isAdmin){if(tab==='home')content=<HomeResident/>;else if(tab==='report')content=<ResidentReport currentUser={currentUser} onSubmitSuccess={id=>{setTrackedCaseId(id);refresh()}} onViewCase={id=>{setTrackedCaseId(id);setTab('issues')}}/>;else if(tab==='issues')content=<ResidentTracking complaint={tracked} currentUser={currentUser} onBack={()=>setTab('home')} onRefreshComplaint={refresh}/>;else if(tab==='manual')content=<AppManual language={language}/>;else if(tab==='chat')content=<ChatRoom currentUser={currentUser} language={language}/>;else if(tab==='notifications')content=<Notifications/>;else if(tab==='notices')content=<NoticeBoard user={currentUser} notices={notices} onCreate={createNotice}/>;else content=<Profile/>;}
 else {if(tab==='dashboard'||tab==='issues')content=<CommandCenter complaints={complaints} masterIssues={masterIssues} currentUser={currentUser} onOpenIssue={setActiveComplaint} onOpenMaster={setActiveMaster} onOpenTwoMinuteTriage={()=>setIsTriageOpen(true)} onOpenResolution={setResolvingComplaint} onRefresh={refresh}/>;else if(tab==='insights')content=<SocietyPulse complaints={complaints} onCreateMaintenanceTask={createTask}/>;else if(tab==='galaxy')content=defaultMaster?<IssueGalaxy masterIssue={defaultMaster} allComplaints={complaints} onSelectComplaint={setActiveComplaint} onSelectMaster={setActiveMaster}/>:<div className="p-10 text-center">No master issues yet.</div>;else if(tab==='notices')content=<NoticeBoard user={currentUser} notices={notices} onCreate={createNotice}/>;else if(tab==='notifications')content=<Notifications/>;else content=<ReminderCenter user={currentUser} reminders={reminders} onCreate={createReminder} onUpdate={updateReminder}/>;}
 return <div className="min-h-screen bg-[#FFF9F8] text-slate-900"><PortalNav user={currentUser} tab={tab} onTab={setTab} unread={unread} onLogout={logout} onSearch={()=>setIsSearchOpen(true)} language={language} onLanguageChange={setLang}/><main className="pb-20 lg:pb-0">{content}</main>{activeComplaint&&<IssueIntelligenceModal complaint={activeComplaint} currentUser={currentUser} onClose={()=>setActiveComplaint(null)} onOpenResolution={cc=>{setActiveComplaint(null);setResolvingComplaint(cc)}} onRefresh={refresh}/>} {resolvingComplaint&&<ResolutionModal complaint={resolvingComplaint} currentUser={currentUser} onClose={()=>setResolvingComplaint(null)} onSuccess={refresh}/>} {activeMaster&&<MasterIssueModal masterIssue={activeMaster} allComplaints={complaints} onClose={()=>setActiveMaster(null)} onOpenComplaint={setActiveComplaint}/>} {isTriageOpen&&<TwoMinuteTriage complaints={complaints} currentUser={currentUser} onClose={()=>setIsTriageOpen(false)} onOpenIssue={setActiveComplaint} onAssignQuick={async cc=>{await api.updateComplaint(cc.id,{assigned_to:'Rohan Sharma (Maintenance Lead)',status:'IN_PROGRESS'});refresh()}} onResolveQuick={cc=>{setIsTriageOpen(false);setResolvingComplaint(cc)}} onMergeQuick={()=>{setIsTriageOpen(false);setActiveMaster(defaultMaster)}}/>}<SearchModal complaints={complaints} isOpen={isSearchOpen} onClose={()=>setIsSearchOpen(false)} onSelectComplaint={setActiveComplaint}/></div>;
}
function ClipboardListIcon(){return <div className="w-14 h-14 rounded-2xl bg-rose-50 text-rose-500 mx-auto flex items-center justify-center"><CheckCircle2 className="w-7 h-7"/></div>}
export default App;
